spring:
  jpa:
    database: h2
    open-in-view: false
  resources:
    add-mappings: true # disable the default frontend when you use only the backend server

server:
  port: 8070

jwt:
  secret: Zq4t7w!z%C*F-JaNdRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfT
  header: Authorization
  prefix: Bearer
  type: jwt
  issuer: authentication-server
  audience: authenticated-app
  expireAfter: 120000 # 2 minutes
